# {{EMOJI}} {{APP_NAME}} — Android wrapper

Capacitor wrapper that packages the [{{SLUG}}](https://github.com/abourdim/{{SLUG}}) trilingual web app as an installable **Android APK** (and **iOS IPA** where applicable).

> {{TITLE_AR}} · {{TITLE_EN}} · {{TITLE_FR}}

{{ABOUT_EN}}

## Quick start

```bash
./manage.sh    # auto-detects your OS, then opens the menu
```

Build, test on emulator, and prepare a Play Store / App Store release from a single guided menu. See [WORKSHOP.html](WORKSHOP.html) for the full step-by-step guide.

## Download the latest APK

[📦 latest release](https://github.com/abourdim/{{SLUG}}-android/releases/latest) · [![QR](releases/download-qr.svg)](https://github.com/abourdim/{{SLUG}}-android/releases/latest)

Scan the QR with an Android phone, or `adb install -r {{SLUG}}-vX.Y-debug.apk`.

## Repo layout

| Item | Notes |
|---|---|
| `www/` | Web app code (synced from [{{SLUG}}](https://github.com/abourdim/{{SLUG}}) at spawn time) |
| `index.html` | Landing page (download APK, QR, links) |
| `WORKSHOP.html` | Build & publish walkthrough |
| `capacitor.config.json` | App ID `{{APP_ID}}`, splash + statusbar themed |
| `package.json` | Capacitor 8.x dependencies |
| `manage.sh` | OS dispatcher → `manage-{linux,macos,windows,ios}.sh` |
| `releases/` | Prebuilt APK artifacts + QR code |
| `store-assets/` | Play Store icon, feature graphic, privacy policy |
| `PLAY_STORE_LISTING.md` | Trilingual store copy (AR / EN / FR), ready to paste |
| `.gitignore` | Excludes `node_modules/`, `android/.gradle/`, keystores |

## Generated by `koutoub-spawn.sh`

This repo was spawned from [koutoub-android-template](https://github.com/abourdim/koutoub-android-template) on **{{DATE}}**. Bug fixes to the build/publish toolchain belong upstream in the template repo, not here.

## License

MIT — see [LICENSE](LICENSE).

— *workshop-diy.org*
